from enum import StrEnum


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class TimeInForce(StrEnum):
    DAY = "DAY"
    GTC = "GTC"
    IOC = "IOC"


class OrderStatus(StrEnum):
    NEW = "NEW"
    VALIDATED = "VALIDATED"
    ROUTED = "ROUTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELLED = "CANCELLED"


class BrokerEventType(StrEnum):
    FULL_FILL = "FULL_FILL"
    PARTIAL_FILL = "PARTIAL_FILL"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class OrderEventType(StrEnum):
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_VALIDATED = "ORDER_VALIDATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    ORDER_ROUTED = "ORDER_ROUTED"
    PARTIAL_FILL_RECEIVED = "PARTIAL_FILL_RECEIVED"
    FULL_FILL_RECEIVED = "FULL_FILL_RECEIVED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_REJECTED = "ORDER_REJECTED"
    BROKER_EVENT_IGNORED = "BROKER_EVENT_IGNORED"
